name: Deploy to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build project
        run: ./gradlew clean build -x test

      - name: Create .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "KAUTH_REST_API_KEY=${{ secrets.KAUTH_REST_API_KEY }}" >> .env
          echo "KAUTH_REST_API_REDIRECT_URI=${{ secrets.KAUTH_REST_API_REDIRECT_URI }}" >> .env
          echo "ACCESS_KEY=${{ secrets.ACCESS_KEY }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> .env
          echo "REGION=${{ secrets.REGION }}" >> .env
          cat .env
          find . -name .env

      - name: Check Files
        run: |
          ls -l 
          ls -l build/libs  

      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./build/libs/${{ secrets.JAR_FILE }}"
          target: "/home/${{ secrets.EC2_USER }}/"
          debug: true

      - name: Copy .env file to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "./.env"
          target: "/home/${{ secrets.EC2_USER }}/build/libs"
          debug: true

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/build/libs
            
            export $(grep -v '^#' .env | xargs)
            
            pkill -f ${{ secrets.JAR_FILE }} || true

            nohup java -jar ${{ secrets.JAR_FILE }} > app.log 2>&1 &